#define T1 "###.\n..#.\n....\n....\n"
#define T2 "....\n....\n##..\n##..\n"
#define T3 "####\n....\n....\n....\n"
#define T4 ".#..\n###.\n....\n....\n"
#define T5 "....\n....\n..##\n..##\n"
#define T6 "....\n..##\n..#.\n..#.\n"